import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { resetConfigCache, CONFIG_DIR_NAME } from '../../../src/lib/config.js';
import { resetPolicyCache } from '../../../src/lib/policy.js';
import { registerProject, resetRegistryCache } from '../../../src/lib/registry.js';
import { executeEnv, formatEnvrc } from '../../../src/lib/command-ops/env-ops.js';

describe('executeEnv', () => {
  let tmpDir: string;
  let configDir: string;
  const origEnv = process.env.PILOTLYNX_ROOT;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'pilotlynx-env-ops-'));
    configDir = join(tmpDir, CONFIG_DIR_NAME);
    process.env.PILOTLYNX_ROOT = configDir;
    resetConfigCache();
    resetPolicyCache();
    resetRegistryCache();

    mkdirSync(join(configDir, 'shared', 'policies'), { recursive: true });
    writeFileSync(join(configDir, 'projects.yaml'), 'version: 1\nprojects: {}\n');
  });

  afterEach(() => {
    if (origEnv !== undefined) process.env.PILOTLYNX_ROOT = origEnv;
    else delete process.env.PILOTLYNX_ROOT;
    rmSync(tmpDir, { recursive: true, force: true });
    resetConfigCache();
    resetPolicyCache();
    resetRegistryCache();
  });

  it('returns error for unregistered project', () => {
    const result = executeEnv('unregistered', {});
    expect(result.success).toBe(false);
    expect(result.error).toContain('not registered');
  });

  it('returns dotenv format by default', () => {
    const projectDir = join(tmpDir, 'proj');
    mkdirSync(projectDir, { recursive: true });
    registerProject('proj', projectDir);

    writeFileSync(join(configDir, '.env'), 'API_KEY=test123\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - API_KEY\nprojects: {}\n'
    );

    const result = executeEnv('proj', {});
    expect(result.success).toBe(true);
    expect(result.output).toContain('API_KEY=');
  });

  it('returns JSON format when requested', () => {
    const projectDir = join(tmpDir, 'proj2');
    mkdirSync(projectDir, { recursive: true });
    registerProject('proj2', projectDir);

    writeFileSync(join(configDir, '.env'), 'TOKEN=abc\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - TOKEN\nprojects: {}\n'
    );

    const result = executeEnv('proj2', { json: true });
    expect(result.success).toBe(true);
    const parsed = JSON.parse(result.output!);
    expect(parsed.TOKEN).toBe('abc');
  });
});

describe('formatEnvrc', () => {
  it('includes PILOTLYNX_ROOT and secrets', () => {
    const output = formatEnvrc({ KEY: 'value' }, '/config/root');
    expect(output).toContain('PILOTLYNX_ROOT=');
    expect(output).toContain('/config/root');
    expect(output).toContain('KEY=');
  });

  it('includes marker comment', () => {
    const output = formatEnvrc({}, '/config/root');
    expect(output).toContain('Generated by PilotLynx');
  });
});
