import { isRegistered } from '../registry.js';
import { buildProjectEnv } from '../secrets.js';
import { getConfigRoot } from '../config.js';
import { shellEscape } from '../shell-escape.js';

export interface EnvOptions {
  export?: boolean;
  json?: boolean;
  envrc?: boolean;
}

export interface EnvResult {
  success: boolean;
  error?: string;
  output?: string;
}

function formatDotenv(env: Record<string, string>): string {
  return Object.entries(env)
    .map(([k, v]) => `${k}="${v.replace(/[\\"$`]/g, '\\$&')}"`)
    .join('\n');
}

function formatExport(env: Record<string, string>): string {
  return Object.entries(env)
    .map(([k, v]) => `export ${k}=${shellEscape(v)}`)
    .join('\n');
}

function formatJson(env: Record<string, string>): string {
  return JSON.stringify(env, null, 2);
}

export function formatEnvrc(env: Record<string, string>, configRoot: string): string {
  const lines = [
    '# Generated by PilotLynx — do not edit',
    '# Re-run: plynx link <project> --direnv',
    `export PILOTLYNX_ROOT=${shellEscape(configRoot)}`,
  ];
  for (const [k, v] of Object.entries(env)) {
    lines.push(`export ${k}=${shellEscape(v)}`);
  }
  return lines.join('\n') + '\n';
}

export function executeEnv(project: string, opts: EnvOptions): EnvResult {
  if (!isRegistered(project)) {
    return { success: false, error: `Project "${project}" is not registered.` };
  }

  const env = buildProjectEnv(project);

  let output: string;
  if (opts.envrc) {
    output = formatEnvrc(env, getConfigRoot());
  } else if (opts.json) {
    output = formatJson(env) + '\n';
  } else if (opts.export) {
    output = formatExport(env);
    if (output) output += '\n';
  } else {
    output = formatDotenv(env);
    if (output) output += '\n';
  }

  return { success: true, output };
}
