import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import YAML from 'yaml';
import { execFileSync } from 'node:child_process';
import { resetConfigCache, CONFIG_DIR_NAME } from '../../src/lib/config.js';
import { resetRegistryCache, registerProject } from '../../src/lib/registry.js';
import { resetPolicyCache } from '../../src/lib/policy.js';

const CLI_PATH = join(process.cwd(), 'dist', 'cli.js');

function runCli(args: string[], env?: Record<string, string>): { output: string; exitCode: number } {
  try {
    const stdout = execFileSync('node', [CLI_PATH, ...args], {
      encoding: 'utf8',
      timeout: 10000,
      stdio: ['pipe', 'pipe', 'pipe'],
      env: { ...process.env, ...env },
    });
    return { output: stdout, exitCode: 0 };
  } catch (err: any) {
    const combined = (err.stdout ?? '') + (err.stderr ?? '');
    return { output: combined || err.message, exitCode: err.status ?? 1 };
  }
}

describe('plynx env command', () => {
  let tmpDir: string;
  let configDir: string;
  const origRoot = process.env.PILOTLYNX_ROOT;

  beforeEach(() => {
    tmpDir = mkdtempSync(join(tmpdir(), 'plynx-env-'));
    configDir = join(tmpDir, CONFIG_DIR_NAME);
    mkdirSync(configDir, { recursive: true });
    mkdirSync(join(configDir, 'shared', 'policies'), { recursive: true });
    writeFileSync(join(configDir, 'plynx.yaml'), YAML.stringify({ version: 1, name: 'test' }));

    // Register a project
    const projectDir = join(tmpDir, 'myproject');
    mkdirSync(projectDir, { recursive: true });
    writeFileSync(
      join(configDir, 'projects.yaml'),
      YAML.stringify({ version: 1, projects: { myproject: { path: 'myproject' } } })
    );
  });

  afterEach(() => {
    if (origRoot !== undefined) process.env.PILOTLYNX_ROOT = origRoot;
    else delete process.env.PILOTLYNX_ROOT;
    rmSync(tmpDir, { recursive: true, force: true });
  });

  const wsEnv = () => ({ PILOTLYNX_ROOT: configDir });

  it('outputs dotenv format by default', () => {
    writeFileSync(join(configDir, '.env'), 'ANTHROPIC_API_KEY=sk-123\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - ANTHROPIC_API_KEY\nprojects: {}\n'
    );

    const { output, exitCode } = runCli(['env', 'myproject'], wsEnv());
    expect(exitCode).toBe(0);
    expect(output.trim()).toBe('ANTHROPIC_API_KEY="sk-123"');
  });

  it('outputs export format with --export', () => {
    writeFileSync(join(configDir, '.env'), 'ANTHROPIC_API_KEY=sk-123\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - ANTHROPIC_API_KEY\nprojects: {}\n'
    );

    const { output, exitCode } = runCli(['env', 'myproject', '--export'], wsEnv());
    expect(exitCode).toBe(0);
    expect(output.trim()).toBe("export ANTHROPIC_API_KEY='sk-123'");
  });

  it('outputs JSON format with --json', () => {
    writeFileSync(join(configDir, '.env'), 'ANTHROPIC_API_KEY=sk-123\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - ANTHROPIC_API_KEY\nprojects: {}\n'
    );

    const { output, exitCode } = runCli(['env', 'myproject', '--json'], wsEnv());
    expect(exitCode).toBe(0);
    const parsed = JSON.parse(output);
    expect(parsed).toEqual({ ANTHROPIC_API_KEY: 'sk-123' });
  });

  it('outputs envrc format with --envrc', () => {
    writeFileSync(join(configDir, '.env'), 'ANTHROPIC_API_KEY=sk-123\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - ANTHROPIC_API_KEY\nprojects: {}\n'
    );

    const { output, exitCode } = runCli(['env', 'myproject', '--envrc'], wsEnv());
    expect(exitCode).toBe(0);
    expect(output).toContain('# Generated by PilotLynx');
    expect(output).toContain(`export PILOTLYNX_ROOT='${configDir}'`);
    expect(output).toContain("export ANTHROPIC_API_KEY='sk-123'");
  });

  it('respects policy filtering', () => {
    writeFileSync(join(configDir, '.env'), 'ANTHROPIC_API_KEY=sk-123\nSECRET=hidden\n');
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - ANTHROPIC_API_KEY\nprojects: {}\n'
    );

    const { output, exitCode } = runCli(['env', 'myproject', '--json'], wsEnv());
    expect(exitCode).toBe(0);
    const parsed = JSON.parse(output);
    expect(parsed).toEqual({ ANTHROPIC_API_KEY: 'sk-123' });
    expect(parsed).not.toHaveProperty('SECRET');
  });

  it('produces empty output when no .env file exists', () => {
    writeFileSync(
      join(configDir, 'shared', 'policies', 'secrets-access.yaml'),
      'version: 1\nshared:\n  - ANTHROPIC_API_KEY\nprojects: {}\n'
    );

    const { output, exitCode } = runCli(['env', 'myproject', '--json'], wsEnv());
    expect(exitCode).toBe(0);
    expect(JSON.parse(output)).toEqual({});
  });

  it('fails for unregistered project', () => {
    const { exitCode, output } = runCli(['env', 'nonexistent'], wsEnv());
    expect(exitCode).toBe(1);
    expect(output).toContain('not registered');
  });
});
